### ISSUE TITLE
failed to compile on armhf (gcc 8.1)

### ISSUE THREAD

**Issue by Askmewho** [AliveTeam/alive_reversing#51]
/home/pi/alive_reversing/Source/AliveLib/Abe.cpp:407:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
 };
 ^
Source/AliveLib/CMakeFiles/AliveLib.dir/build.make:595: fallo en las instrucciones para el objetivo 'Source/AliveLib/CMakeFiles/AliveLib.dir/Abe.cpp.o'
make[2]: *** [Source/AliveLib/CMakeFiles/AliveLib.dir/Abe.cpp.o] Error 1
CMakeFiles/Makefile2:218: fallo en las instrucciones para el objetivo 'Source/AliveLib/CMakeFiles/AliveLib.dir/all'
make[1]: *** [Source/AliveLib/CMakeFiles/AliveLib.dir/all] Error 2
Makefile:162: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

the error its produced here (dont know how to introduce "signed char" if thats the answer)

const TintEntry sTintTable_Abe_554D20[15] =
{
    { 1, 102u, 102u, 102u },
    { 2, 102u, 102u, 80u },
    { 3, 120u, 90u, 120u },
    { 4, 102u, 70u, 90u },
    { 5, 120u, 102u, 82u },
    { 6, 102u, 102u, 102u },
    { 7, 102u, 70u, 90u },
    { 8, 102u, 102u, 102u },
    { 9, 102u, 102u, 102u },
    { 10, 102u, 102u, 102u },
    { 11, 120u, 90u, 120u },
    { 12, 120u, 102u, 82u },
    { 13, 102u, 102u, 102u },
    { 14, 120u, 90u, 80u },
    { -1, 102u, 102u, 102u }
};

**Comment by paulsapps** [comment]
is char unsigned for some reason? you could probably hack fix it by doing static_cast<char>(-1)

**Comment by paulsapps** [comment]
https://stackoverflow.com/questions/31634962/narrowing-conversion-from-int-to-char-inside-for-legal-values-when-cro

Seems like the default value of char is unsigned in your environment. A lot of the code assumes that it will be signed, oops.

The actual fix is probably to change `#define __int8  char` to `#define __int8  signed char`

**Comment by paulsapps** [comment]
I pushed that change and it breaks the build so I've updated just the 1 structure with the issue, give it another go and let me know if it works.

**Comment by Askmewho** [comment]
Its working, I will let you know if it finish

**Comment by Askmewho** [comment]
same issue but on another location haha

/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
 };
 ^
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:54:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:106:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
 };
 ^
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:127:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
 };
 ^
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:148:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
 };
 ^
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:148:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:169:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
 };
 ^
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:169:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:169:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:169:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:169:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:169:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:190:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
 };
 ^
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:190:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:190:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:190:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:190:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:190:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:211:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
 };
 ^
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:211:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:211:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:211:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:211:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/MusicController.cpp:211:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
Source/AliveLib/CMakeFiles/AliveLib.dir/build.make:608: fallo en las instrucciones para el objetivo 'Source/AliveLib/CMakeFiles/AliveLib.dir/MusicController.cpp.o'
make[2]: *** [Source/AliveLib/CMakeFiles/AliveLib.dir/MusicController.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
CMakeFiles/Makefile2:218: fallo en las instrucciones para el objetivo 'Source/AliveLib/CMakeFiles/AliveLib.dir/all'
make[1]: *** [Source/AliveLib/CMakeFiles/AliveLib.dir/all] Error 2
Makefile:162: fallo en las instrucciones para el objetivo 'all'

**Comment by mlgthatsme** [comment]
Can you try building again with the latest commit ?

**Comment by Askmewho** [comment]
oops, again here:

/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
 };
 ^
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-2’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-2’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-2’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-2’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-3’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-3’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-3’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-3’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-9’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-9’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-9’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
/home/pi/alive_reversing/Source/AliveLib/ScreenShake.cpp:96:1: error: narrowing conversion of ‘-9’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
Source/AliveLib/CMakeFiles/AliveLib.dir/build.make:959: fallo en las instrucciones para el objetivo 'Source/AliveLib/CMakeFiles/AliveLib.dir/ScreenShake.cpp.o'
make[2]: *** [Source/AliveLib/CMakeFiles/AliveLib.dir/ScreenShake.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
CMakeFiles/Makefile2:218: fallo en las instrucciones para el objetivo 'Source/AliveLib/CMakeFiles/AliveLib.dir/all'
make[1]: *** [Source/AliveLib/CMakeFiles/AliveLib.dir/all] Error 2
Makefile:162: fallo en las instrucciones para el objetivo 'all'

**Comment by mouzee1337** [comment]
lmao less errors tho 🚀

**Comment by Askmewho** [comment]
one last? 

/home/pi/alive_reversing/Source/AliveLib/Gibs.cpp:31:1: error: narrowing conversion of ‘'\377'’ from ‘char’ to ‘signed char’ inside { } [-Wnarrowing]
 };
 ^
Source/AliveLib/CMakeFiles/AliveLib.dir/build.make:985: fallo en las instrucciones para el objetivo 'Source/AliveLib/CMakeFiles/AliveLib.dir/Gibs.cpp.o'
make[2]: *** [Source/AliveLib/CMakeFiles/AliveLib.dir/Gibs.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
CMakeFiles/Makefile2:218: fallo en las instrucciones para el objetivo 'Source/AliveLib/CMakeFiles/AliveLib.dir/all'
make[1]: *** [Source/AliveLib/CMakeFiles/AliveLib.dir/all] Error 2
Makefile:162: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

**Comment by paulsapps** [comment]
Don' worry about the time - these are correctness issues that would need fixing at some point anyway.

**Comment by Askmewho** [comment]
[ 20%] Building CXX object Source/AliveLib/CMakeFiles/AliveLib.dir/StatusLight.cpp.o
[ 21%] Building CXX object Source/AliveLib/CMakeFiles/AliveLib.dir/WheelSyncer.cpp.o
[ 21%] Building CXX object Source/AliveLib/CMakeFiles/AliveLib.dir/LevelLoader.cpp.o
[ 22%] Building CXX object Source/AliveLib/CMakeFiles/AliveLib.dir/InvisibleSwitch.cpp.o
[ 23%] Building CXX object Source/AliveLib/CMakeFiles/AliveLib.dir/Switch.cpp.o
/home/pi/alive_reversing/Source/AliveLib/Switch.cpp:32:1: error: narrowing conversion of ‘'\377'’ from ‘char’ to ‘signed char’ inside { } [-Wnarrowing]
 };
 ^
[ 24%] Building CXX object Source/AliveLib/CMakeFiles/AliveLib.dir/MultiSwitchController.cpp.o
Source/AliveLib/CMakeFiles/AliveLib.dir/build.make:1284: fallo en las instrucciones para el objetivo 'Source/AliveLib/CMakeFiles/AliveLib.dir/Switch.cpp.o'
make[2]: *** [Source/AliveLib/CMakeFiles/AliveLib.dir/Switch.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
CMakeFiles/Makefile2:218: fallo en las instrucciones para el objetivo 'Source/AliveLib/CMakeFiles/AliveLib.dir/all'
make[1]: *** [Source/AliveLib/CMakeFiles/AliveLib.dir/all] Error 2
Makefile:162: fallo en las instrucciones para el objetivo 'all'

**Comment by Askmewho** [comment]
fixed!

**Comment by Askmewho** [comment]
offtopic: Ive get a seg fault on startup.

AliveExe  AliveExe.cmake  CMakeFiles  cmake_install.cmake  CTestTestfile.cmake  Makefile
pi@pi:~/alive_reversing/build/Source/AliveExe $ ./AliveExe 
2019-03-20 13:45:59,305 WARNING [default] BaseAnimatedWithPhysicsGameObject::BaseAnimatedWithPhysicsGameObject() [W] Exists only to make things build - func may break behaviour of objects
2019-03-20 13:45:59,324 INFO [default] int WinMain_4EE631(HINSTANCE, HINSTANCE, LPSTR, int) [I] Main enter
2019-03-20 13:45:59,362 WARNING [default] int PSX_CD_Add_EMU_Path_4FAC00(const char*) [W] Not implemented
2019-03-20 13:46:00,081 WARNING [default] void PSX_EMU_Set_screen_mode_4F9420(char) [W] Not implemented
2019-03-20 13:46:00,081 INFO [default] int VGA_FullScreenSet_4F31F0(bool) [I] Stub
2019-03-20 13:46:00,308 WARNING [default] void VLC_Tables_Init_496720() [W] Not implemented
2019-03-20 13:46:00,322 WARNING [default] void sub_4FBA20() [W] Not implemented
2019-03-20 13:46:00,322 WARNING [default] void CheckShiftCapslock_4953B0() [W] Not implemented
2019-03-20 13:46:00,322 WARNING [default] void Draw_Debug_Strings_4F2800() [W] Not implemented
SDL Audio Driver 0: pulseaudio
SDL Audio Driver 1: alsa
SDL Audio Driver 2: sndio
SDL Audio Driver 3: dsp
SDL Audio Driver 4: disk
SDL Audio Driver 5: dummy
2019-03-20 13:46:00,483 WARNING [default] void Init_GameStates_43BF40() [W] Not implemented
Violación de segmento

**Comment by Askmewho** [comment]
its very hard for debug for sure, so I will test again on other arm sbc on next mounths, thanks anyway.

**Comment by paulsapps** [comment]
Do you have the game data in ~/alive_reversing/build/Source/AliveExe ?

**Comment by Askmewho** [comment]
No. I doesnt, but that could not give me a segfault. It should only said than there are files missing. I am wrong??

**Comment by paulsapps** [comment]
As this is the same as the original Windows game I believe that just crashes without data. It will be made better once we reach 100% of functions implemented.

**Comment by paulsapps** [comment]
For your other questions - 

What are your plans when thats where ready??
- I'm not sure what you mean by this. Can you explain?

I seen than there is an hd remake, it uses the same engine??
- No this is a reversing project of the original Abe's Exoddus.

**Comment by paulsapps** [comment]
Let me know if it starts when the game data exists - then I can close this issue.

**Comment by Askmewho** [comment]
hey!!! It works! well done devs. it have minor slowdowns and some issue with sound (doesnt sound correctly) I will do a short video of demonstration on my channel. 

btw, I am on a mighty RPI3 haha

**Comment by Askmewho** [comment]
please, close it if you want. thanks and please continue developing these...

**Comment by paulsapps** [comment]
Awesome, do send a link to the video when its up 👍

**Comment by Askmewho** [comment]
https://youtu.be/dn0BFgSjzA8

Sorry for the low quality. I will make a proper video when this gets a bit more developed. But just for demonstration its ok. The sound could be an alsa problem related. I will give you a better feedback later. But it works, and thats the important thing.

**Comment by Askmewho** [comment]
just if you found it useful i will paste the log. but i believe you need some more complex tracing tools (like apitrace,etc).

pi@pi:~/alive_reversing/build/Source/AliveExe $ ./AliveExe
2019-03-20 22:25:35,431 WARNING [default] BaseAnimatedWithPhysicsGameObject::BaseAnimatedWithPhysicsGameObject() [W] Exists only to make things build - func may break behaviour of objects
2019-03-20 22:25:35,434 INFO [default] int WinMain_4EE631(HINSTANCE, HINSTANCE, LPSTR, int) [I] Main enter
2019-03-20 22:25:35,442 WARNING [default] int PSX_CD_Add_EMU_Path_4FAC00(const char*) [W] Not implemented
2019-03-20 22:25:35,725 WARNING [default] void PSX_EMU_Set_screen_mode_4F9420(char) [W] Not implemented
2019-03-20 22:25:35,726 INFO [default] int VGA_FullScreenSet_4F31F0(bool) [I] Stub
2019-03-20 22:25:35,903 WARNING [default] void VLC_Tables_Init_496720() [W] Not implemented
2019-03-20 22:25:35,906 WARNING [default] void sub_4FBA20() [W] Not implemented
2019-03-20 22:25:35,906 WARNING [default] void CheckShiftCapslock_4953B0() [W] Not implemented
2019-03-20 22:25:35,906 WARNING [default] void Draw_Debug_Strings_4F2800() [W] Not implemented
SDL Audio Driver 0: pulseaudio
SDL Audio Driver 1: alsa
SDL Audio Driver 2: sndio
SDL Audio Driver 3: dsp
SDL Audio Driver 4: disk
SDL Audio Driver 5: dummy
2019-03-20 22:25:36,007 WARNING [default] void Init_GameStates_43BF40() [W] Not implemented
Category: Control Layout
Value: controller is Keyboard
Category: Keyboard
2019-03-20 22:25:36,038 WARNING [default] void Input_ResetBinding_4925A0(int, int) [W] Not implemented
Value: run is lol
Value: sneak is lol
Value: jump is lol
Value: action is lol
Value: throw is lol
Value: fart is lol
Category: Game Pad
Value: buttons is 0
Value: run is lol
Value: sneak is lol
Value: jump is lol
Value: action is lol
Value: throw is lol
Value: fart is lol
Value: speak1 is lol
Value: speak2 is lol
Category: ALIVE
Value: keep_aspect is false
Value: filter_screen is true
Value: reverb is true
2019-03-20 22:25:36,039 WARNING [default] void Input_491870() [W] Not implemented
2019-03-20 22:25:36,080 WARNING [default] int MainMenuController::sub_4CF640() [W] Not implemented
2019-03-20 22:25:36,081 WARNING [default] void MainMenuController::sub_4CFE80() [W] Not implemented
2019-03-20 22:25:36,081 WARNING [default] void ScreenManager::sub_40EE50() [W] Not implemented
2019-03-20 22:25:36,081 WARNING [default] void ScreenManager::sub_40EE10() [W] Not implemented
2019-03-20 22:25:41,912 WARNING [default] void Add_Dirty_Area_4ED970(int, int, int, int) [W] Not implemented
2019-03-20 22:25:47,816 WARNING [default] void Map::sub_480740(short int) [W] Not implemented
2019-03-20 22:25:47,816 WARNING [default] void Factory_Null_4D6910(Path_TLV*, Path*, TlvItemInfoUnion, short int) [W] Not implemented
2019-03-20 22:25:52,970 WARNING [default] void Animation::Get_Frame_Rect_409E10(PSX_RECT*) [W] Not implemented
2019-03-20 22:26:02,088 WARNING [default] short int sub_4A2BC0() [W] Not implemented
2019-03-20 22:26:02,323 WARNING [default] void Factory_InvisibleZone_4D6A40(Path_TLV*, Path*, TlvItemInfoUnion, short int) [W] Not implemented
2019-03-20 22:26:02,323 WARNING [default] void Factory_BirdPortal_4D9AA0(Path_TLV*, Path*, TlvItemInfoUnion, short int) [W] Not implemented
2019-03-20 22:26:02,324 WARNING [default] void Factory_ContinuePoint_4D6970(Path_TLV*, Path*, TlvItemInfoUnion, short int) [W] Not implemented
2019-03-20 22:26:02,338 WARNING [default] void Factory_Mudokon_4D8EC0(Path_TLV*, Path*, TlvItemInfoUnion, short int) [W] Not implemented
2019-03-20 22:26:02,339 WARNING [default] void Factory_ZSligCover_4D6A60(Path_TLV*, Path*, TlvItemInfoUnion, short int) [W] Not implemented
2019-03-20 22:26:02,339 WARNING [default] void Factory_SligPersist_4D79D0(Path_TLV*, Path*, TlvItemInfoUnion, short int) [W] Not implemented
2019-03-20 22:26:02,339 WARNING [default] void Factory_EnemyStopper_4D6AC0(Path_TLV*, Path*, TlvItemInfoUnion, short int) [W] Not implemented
2019-03-20 22:26:02,339 WARNING [default] void Factory_SligBoundRight_4D79A0(Path_TLV*, Path*, TlvItemInfoUnion, short int) [W] Not implemented
2019-03-20 22:26:02,339 WARNING [default] void Factory_Slig_4D7BC0(Path_TLV*, Path*, TlvItemInfoUnion, short int) [W] Not implemented
2019-03-20 22:26:02,339 WARNING [default] void Factory_SoftLanding_4D6950(Path_TLV*, Path*, TlvItemInfoUnion, short int) [W] Not implemented
2019-03-20 22:26:02,339 WARNING [default] const char* Input_GetButtonString_492530(const char*, int) [W] Not implemented
2019-03-20 22:26:12,275 WARNING [default] void Start_Sounds_for_TLV_4CB530(short int, Path_TLV*) [W] Not implemented
2019-03-20 22:26:12,276 WARNING [default] int Abe::vGetSaveState_457110(BYTE*) [W] Not implemented
2019-03-20 22:26:12,307 WARNING [default] void Quicksave_SaveToMemory_4C91A0(Quicksave*) [W] Not implemented
2019-03-20 22:26:12,308 WARNING [default] int sub_4561B0(void*, short int*) [W] Not implemented
2019-03-20 22:26:12,862 WARNING [default] int Abe_SFX_2_457A40(char, int, int, BaseAliveGameObject*) [W] Not implemented
2019-03-20 22:26:20,181 WARNING [default] short int Abe::sub_44EC10() [W] Not implemented
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
2019-03-20 22:26:44,553 WARNING [default] BaseGameObject* Abe::vsub_44E970(short int) [W] Not implemented
2019-03-20 22:26:52,316 WARNING [default] void Factory_SligBoundLeft_4D7740(Path_TLV*, Path*, TlvItemInfoUnion, short int) [W] Not implemented
